function TotChar=QuestionsArrayF
% This program will load all of the bird characteristics and place them
% into a cell array of strings.
% Author: Group 11, Bird Identifier


%% Load text file
TotChar={'Swimming',...
'Walking, wading, running',...
'Hopping or climbing',...
'Still perching',...
'Continuous flying',...
'Larger than robin',...
'About same size as robin',...
'Smaller than robin',...
'Neck long',...
'Tail long',...
'Tail forked',...
'Bill long, as long or longer than head',...
'Bill thick, as thick or thicker at base than length of bill',...
'Head crested',...
'Mostly white',...
'Mostly blackish, or dark gray, bluish black, etc.',...
'Mostly black and white, or other dark color and white',...
'Mostly brownish, or with many brown streaks or spots',...
'Mostly dull green or brownish green',...
'Rust color present',...
'Red present',...
'Yellow or orange',...
'Blue or bright green (not dull green)',...
'Round spots on body',...
'Streaks (long spots)',...
'Cross barring',...
'Underparts plain',...
'Bold markings present (patches or blotches of black, white, or color)',...
'Head stripes or bands',...
'Crown patch',...
'Eye ring',...
'Tail stripes (along)',...
'Tail bands (across)',...
'Wing bands or bars',...
'North summer (June through August)',...
'North winter (November through February)',...
'South summer (June through August)',...
'South winter (November through February)',...
'Wood habitat',...
'Field habitat',...
'Marsh habitat',...
'Flats or beach habitat',...
'Continuous flying high (near or above treetops when flying)',...
'Continuous flying low (below treetops when flying)',...
'Perched high (generally above middle of trees when perched or foraging)',...
'Perched low (generally below middle of trees when perched or foraging)',...
'On ground (walking, wading, running, hopping, or resting on ground)',...
'Soaring flight (gliding or circling on set wings)',...
'Zig zag flight (many irregular twists and turns)',...
'Bounding flight',...
'Short forays (flies out from perch and returns)',...
'Jerks tail or body (repeated dipping of body, or flipping or pumping of tail)',...
'Occurs in flocks (from 4 or 5 to thousands)',...
'Rasping harsh calls',...
'Smooth, clear calls (can be imitated by human singing voice or whistling)',...
'Soft, low calls',...
'Staccato and twitter call (short sharp notes or rapid series of notes: tinkling, trilling, sputtering, or percussive)',...
'High or thin song (high pitched and weak; lisping, sizzling, or hissing quality)',...
'Harsh or buzzy song (pitch intermediate; rasping, buzzing, or grating quality)',...
'Melodious song (pitch variable; smooth, sweet, or rich quality; pattern generally complex)'};
